import { defineObject, FieldType, NumberDataType, RelationType } from 'twenty-sdk/define';
import { FIELD_IDS, OBJECT_IDS } from 'src/constants/schema-identifiers';

export default defineObject({
  universalIdentifier: OBJECT_IDS.aiRun,
  nameSingular: 'aiRun',
  namePlural: 'aiRuns',
  labelSingular: 'AI Run',
  labelPlural: 'AI Runs',
  icon: 'IconRefresh',
  labelIdentifierFieldMetadataUniversalIdentifier: FIELD_IDS['aiRun.runKey'],
  fields: [
    { universalIdentifier: FIELD_IDS['aiRun.requestVersion'], name: 'requestVersion', label: 'Request Version', type: FieldType.NUMBER, isNullable: false, defaultValue: 0, universalSettings: { dataType: NumberDataType.INT } },
    { universalIdentifier: FIELD_IDS['aiRun.runKey'], name: 'runKey', label: 'Run Key', type: FieldType.TEXT, isNullable: false, defaultValue: "''" },
    { universalIdentifier: FIELD_IDS['aiRun.status'], name: 'status', label: 'Status', type: FieldType.SELECT, options: [{position:0,label:'RUNNING',value:'RUNNING'},{position:1,label:'WAITING',value:'WAITING'},{position:2,label:'SUCCEEDED',value:'SUCCEEDED'},{position:3,label:'FAILED',value:'FAILED'},{position:4,label:'CANCELLED',value:'CANCELLED'}], isNullable: false, defaultValue: "'RUNNING'" },
    { universalIdentifier: FIELD_IDS['aiRun.threadId'], name: 'threadId', label: 'Thread ID', type: FieldType.TEXT, isNullable: true },
    { universalIdentifier: FIELD_IDS['aiRun.turnId'], name: 'turnId', label: 'Turn ID', type: FieldType.TEXT, isNullable: true },
    { universalIdentifier: FIELD_IDS['aiRun.activeAgentKey'], name: 'activeAgentKey', label: 'Active Agent Key', type: FieldType.TEXT, isNullable: true },
    { universalIdentifier: FIELD_IDS['aiRun.assignmentVersion'], name: 'assignmentVersion', label: 'Assignment Version', type: FieldType.NUMBER, isNullable: true, universalSettings: { dataType: NumberDataType.INT } },
    { universalIdentifier: FIELD_IDS['aiRun.phase'], name: 'phase', label: 'Phase', type: FieldType.SELECT, options: [{position:0,label:'CLAIMED',value:'CLAIMED'},{position:1,label:'STARTING',value:'STARTING'},{position:2,label:'REVIEW',value:'REVIEW'},{position:3,label:'QA',value:'QA'}], isNullable: true },
    { universalIdentifier: FIELD_IDS['aiRun.progressSummary'], name: 'progressSummary', label: 'Progress Summary', type: FieldType.TEXT, isNullable: true },
    { universalIdentifier: FIELD_IDS['aiRun.branchName'], name: 'branchName', label: 'Branch Name', type: FieldType.TEXT, isNullable: true },
    { universalIdentifier: FIELD_IDS['aiRun.prUrl'], name: 'prUrl', label: 'PR URL', type: FieldType.TEXT, isNullable: true },
    { universalIdentifier: FIELD_IDS['aiRun.prNumber'], name: 'prNumber', label: 'PR Number', type: FieldType.NUMBER, isNullable: true, universalSettings: { dataType: NumberDataType.INT } },
    { universalIdentifier: FIELD_IDS['aiRun.headCommit'], name: 'headCommit', label: 'Head Commit', type: FieldType.TEXT, isNullable: true },
    { universalIdentifier: FIELD_IDS['aiRun.workflowVersionId'], name: 'workflowVersionId', label: 'Workflow Version ID', type: FieldType.TEXT, isNullable: true },
    { universalIdentifier: FIELD_IDS['aiRun.inputSnapshot'], name: 'inputSnapshot', label: 'Input Snapshot', type: FieldType.RAW_JSON, isNullable: true },
    { universalIdentifier: FIELD_IDS['aiRun.langfuseTraceId'], name: 'langfuseTraceId', label: 'Langfuse Trace ID', type: FieldType.TEXT, isNullable: true },
    { universalIdentifier: FIELD_IDS['aiRun.langfuseTraceUrl'], name: 'langfuseTraceUrl', label: 'Langfuse Trace URL', type: FieldType.TEXT, isNullable: true },
    { universalIdentifier: FIELD_IDS['aiRun.reviewDecision'], name: 'reviewDecision', label: 'Review Decision', type: FieldType.SELECT, options: [{position:0,label:'ACCEPT',value:'ACCEPT'},{position:1,label:'REWORK',value:'REWORK'}], isNullable: true },
    { universalIdentifier: FIELD_IDS['aiRun.reviewReason'], name: 'reviewReason', label: 'Review Reason', type: FieldType.RICH_TEXT, isNullable: true },
    { universalIdentifier: FIELD_IDS['aiRun.reviewedAt'], name: 'reviewedAt', label: 'Reviewed At', type: FieldType.DATE_TIME, isNullable: true },
    { universalIdentifier: FIELD_IDS['aiRun.startedAt'], name: 'startedAt', label: 'Started At', type: FieldType.DATE_TIME, isNullable: true },
    { universalIdentifier: FIELD_IDS['aiRun.finishedAt'], name: 'finishedAt', label: 'Finished At', type: FieldType.DATE_TIME, isNullable: true },
    { universalIdentifier: FIELD_IDS['aiRun.lastHeartbeatAt'], name: 'lastHeartbeatAt', label: 'Last Heartbeat At', type: FieldType.DATE_TIME, isNullable: true },
    { universalIdentifier: FIELD_IDS['aiRun.waitingReason'], name: 'waitingReason', label: 'Waiting Reason', type: FieldType.SELECT, options: [{position:0,label:'INPUT',value:'INPUT'},{position:1,label:'APPROVAL',value:'APPROVAL'},{position:2,label:'REVIEW',value:'REVIEW'},{position:3,label:'ERROR',value:'ERROR'},{position:4,label:'RECOVERY',value:'RECOVERY'}], isNullable: true },
    { universalIdentifier: FIELD_IDS['aiRun.question'], name: 'question', label: 'Question', type: FieldType.RICH_TEXT, isNullable: true },
    { universalIdentifier: FIELD_IDS['aiRun.answer'], name: 'answer', label: 'Answer', type: FieldType.RICH_TEXT, isNullable: true },
    { universalIdentifier: FIELD_IDS['aiRun.summary'], name: 'summary', label: 'Summary', type: FieldType.RICH_TEXT, isNullable: true },
    { universalIdentifier: FIELD_IDS['aiRun.resultUrl'], name: 'resultUrl', label: 'Result URL', type: FieldType.TEXT, isNullable: true },
    { universalIdentifier: FIELD_IDS['aiRun.errorCode'], name: 'errorCode', label: 'Error Code', type: FieldType.TEXT, isNullable: true },
    { universalIdentifier: FIELD_IDS['aiRun.task'], name: 'task', label: 'Task', type: FieldType.RELATION, isNullable: false, relationTargetObjectMetadataUniversalIdentifier: OBJECT_IDS.aiTask, relationTargetFieldMetadataUniversalIdentifier: FIELD_IDS['aiTask.runs'], universalSettings: { relationType: RelationType.MANY_TO_ONE, joinColumnName: 'taskId' } },
    { universalIdentifier: FIELD_IDS['aiRun.activeForTasks'], name: 'activeForTasks', label: 'Active For Tasks', type: FieldType.RELATION, isNullable: true, relationTargetObjectMetadataUniversalIdentifier: OBJECT_IDS.aiTask, relationTargetFieldMetadataUniversalIdentifier: FIELD_IDS['aiTask.activeRun'], universalSettings: { relationType: RelationType.ONE_TO_MANY } },
    { universalIdentifier: FIELD_IDS['aiRun.journalEntries'], name: 'journalEntries', label: 'Journal Entries', type: FieldType.RELATION, isNullable: true, relationTargetObjectMetadataUniversalIdentifier: OBJECT_IDS.aiRunJournal, relationTargetFieldMetadataUniversalIdentifier: FIELD_IDS['aiRunJournal.run'], universalSettings: { relationType: RelationType.ONE_TO_MANY } }
  ],
});
